<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PosDataSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('roles')->count() === 0) {
            DB::table('roles')->insert(array (
  0 => 
  array (
    'id_role' => 1,
    'nama_role' => 'super admin',
  ),
  1 => 
  array (
    'id_role' => 2,
    'nama_role' => 'admin',
  ),
  2 => 
  array (
    'id_role' => 3,
    'nama_role' => 'kasir',
  ),
  3 => 
  array (
    'id_role' => 4,
    'nama_role' => 'developer',
  ),
));
        }

        if (DB::table('tb_sekolah')->count() === 0) {
            DB::table('tb_sekolah')->insert(array (
  0 => 
  array (
    'id_sekolah' => 1,
    'kode_sekolah' => 'SMKN001',
    'nama_sekolah' => 'SMKN 1 Tasikmalaya',
    'alamat_sekolah' => NULL,
    'website' => 'https://smkn1-tasikmalaya.sch.id',
    'is_active' => 1,
    'created_at' => '2026-09-08 08:23:34',
    'alamat' => 'Jl. Rumah Sakit No. 1 Tasikmalaya',
  ),
  1 => 
  array (
    'id_sekolah' => 2,
    'kode_sekolah' => 'SMKN002',
    'nama_sekolah' => 'SMKN 2 Tasikmalaya',
    'alamat_sekolah' => NULL,
    'website' => 'https://smkn2-tasikmalaya.sch.id',
    'is_active' => 1,
    'created_at' => '2026-09-08 08:23:34',
    'alamat' => 'Jl. Noenoeng Tisnasaputra No. 10 Tasikmalaya',
  ),
  2 => 
  array (
    'id_sekolah' => 3,
    'kode_sekolah' => 'SMKN003',
    'nama_sekolah' => 'SMKN 3 Tasikmalaya',
    'alamat_sekolah' => NULL,
    'website' => 'https://smkn3-tasikmalaya.sch.id',
    'is_active' => 1,
    'created_at' => '2026-09-08 08:23:34',
    'alamat' => 'Jl. Tamansari No. 50 Tasikmalaya',
  ),
  3 => 
  array (
    'id_sekolah' => 4,
    'kode_sekolah' => 'SMKN004',
    'nama_sekolah' => 'SMKN 4 Tasikmalaya',
    'alamat_sekolah' => NULL,
    'website' => 'https://smkn4-tasikmalaya.sch.id',
    'is_active' => 1,
    'created_at' => '2026-09-08 08:23:34',
    'alamat' => 'Jl. Depok No. 1 Tasikmalaya',
  ),
  4 => 
  array (
    'id_sekolah' => 6,
    'kode_sekolah' => 'SMPN01',
    'nama_sekolah' => 'SMPN 1 TASIKMALAYA',
    'alamat_sekolah' => 'Jalan Oto Iskandardinata No. 21, Kelurahan Empangsari, Kecamatan Tawang, Kota Tasikmalaya, Jawa Barat',
    'website' => 'https://www.smpnegeri1tasikmalaya.sch.id',
    'is_active' => 1,
    'created_at' => '2026-09-14 11:30:05',
    'alamat' => NULL,
  ),
));
        }

        if (DB::table('tb_kelompok_kategori')->count() === 0) {
            DB::table('tb_kelompok_kategori')->insert(array (
  0 => 
  array (
    'id_kelompok' => 1,
    'id_sekolah' => 1,
    'nama_kelompok' => 'Alat Tulis',
    'created_at' => '2026-09-08 09:27:54',
    'created_by' => NULL,
  ),
  1 => 
  array (
    'id_kelompok' => 2,
    'id_sekolah' => 1,
    'nama_kelompok' => 'Makanan dan Minuman',
    'created_at' => '2026-09-08 09:27:54',
    'created_by' => NULL,
  ),
  2 => 
  array (
    'id_kelompok' => 3,
    'id_sekolah' => 1,
    'nama_kelompok' => 'Perlengkapan Sekolah',
    'created_at' => '2026-09-08 09:27:54',
    'created_by' => NULL,
  ),
  3 => 
  array (
    'id_kelompok' => 5,
    'id_sekolah' => 2,
    'nama_kelompok' => 'Makanan dan minuman',
    'created_at' => '2026-09-09 08:07:35',
    'created_by' => 1,
  ),
  4 => 
  array (
    'id_kelompok' => 9,
    'id_sekolah' => 2,
    'nama_kelompok' => 'Alat tulis',
    'created_at' => '2026-09-09 14:07:43',
    'created_by' => 1,
  ),
  5 => 
  array (
    'id_kelompok' => 10,
    'id_sekolah' => 2,
    'nama_kelompok' => 'Pakaian siswa',
    'created_at' => '2026-09-09 14:16:18',
    'created_by' => 1,
  ),
  6 => 
  array (
    'id_kelompok' => 11,
    'id_sekolah' => 2,
    'nama_kelompok' => 'Atribut Siswa',
    'created_at' => '2026-09-11 00:18:26',
    'created_by' => 1,
  ),
));
        }

        if (DB::table('tb_kategori')->count() === 0) {
            DB::table('tb_kategori')->insert(array (
  0 => 
  array (
    'id_kategori' => 1,
    'id_kelompok' => 1,
    'nama' => 'Alat Tulis',
    'created_at' => '2026-09-09 09:42:03',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:42:03',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:42:03',
    'deleted_by' => 0,
    'is_deleted' => 0,
  ),
  1 => 
  array (
    'id_kategori' => 2,
    'id_kelompok' => 5,
    'nama' => 'makanan kantin',
    'created_at' => '2026-09-09 08:07:45',
    'created_by' => 1,
    'updated_at' => '2026-09-09 08:07:45',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 13:54:42',
    'deleted_by' => 1,
    'is_deleted' => 1,
  ),
  2 => 
  array (
    'id_kategori' => 3,
    'id_kelompok' => 5,
    'nama' => 'tes',
    'created_at' => '2026-09-09 13:42:50',
    'created_by' => 1,
    'updated_at' => '2026-09-09 13:42:50',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 13:49:47',
    'deleted_by' => 1,
    'is_deleted' => 1,
  ),
  3 => 
  array (
    'id_kategori' => 4,
    'id_kelompok' => 5,
    'nama' => 'makanan ringan',
    'created_at' => '2026-09-09 14:08:43',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:08:43',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_deleted' => 0,
  ),
  4 => 
  array (
    'id_kategori' => 5,
    'id_kelompok' => 5,
    'nama' => 'minuman',
    'created_at' => '2026-09-09 14:08:52',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:08:52',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_deleted' => 0,
  ),
  5 => 
  array (
    'id_kategori' => 6,
    'id_kelompok' => 9,
    'nama' => 'Alat Belajar',
    'created_at' => '2026-09-09 14:09:05',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:15:58',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_deleted' => 0,
  ),
  6 => 
  array (
    'id_kategori' => 7,
    'id_kelompok' => 10,
    'nama' => 'Atribut siswa',
    'created_at' => '2026-09-09 14:16:34',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:16:34',
    'updated_by' => 1,
    'deleted_at' => '2026-09-11 00:18:06',
    'deleted_by' => 1,
    'is_deleted' => 1,
  ),
  7 => 
  array (
    'id_kategori' => 8,
    'id_kelompok' => 10,
    'nama' => 'Baju sekolah siswa',
    'created_at' => '2026-09-09 14:16:51',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:16:51',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_deleted' => 0,
  ),
  8 => 
  array (
    'id_kategori' => 9,
    'id_kelompok' => 11,
    'nama' => 'Atribut Pakaian',
    'created_at' => '2026-09-11 00:18:57',
    'created_by' => 1,
    'updated_at' => '2026-09-11 00:18:57',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_deleted' => 0,
  ),
));
        }

        if (DB::table('tb_supplier')->count() === 0) {
            DB::table('tb_supplier')->insert(array (
  0 => 
  array (
    'id_supplier' => 1,
    'id_sekolah' => 1,
    'nama' => 'CV Sumber ATK',
    'no_telepon' => '081234567890',
    'alamat_supplier' => 'Jl. Raya Tasikmalaya No. 10',
    'created_at' => '2026-09-09 09:42:45',
    'created_by' => 1,
    'deleted_at' => '2026-09-09 09:42:45',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  1 => 
  array (
    'id_supplier' => 2,
    'id_sekolah' => 2,
    'nama' => 'Grosir makanan dan minuman',
    'no_telepon' => '08234572',
    'alamat_supplier' => 'jl kemuning',
    'created_at' => '2026-09-09 08:09:10',
    'created_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  2 => 
  array (
    'id_supplier' => 3,
    'id_sekolah' => 2,
    'nama' => 'Toko alat tulis',
    'no_telepon' => '083242393',
    'alamat_supplier' => 'jl. pancasila',
    'created_at' => '2026-09-09 14:07:02',
    'created_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  3 => 
  array (
    'id_supplier' => 4,
    'id_sekolah' => 2,
    'nama' => 'toko baju & atribut garuda mas',
    'no_telepon' => '083242371',
    'alamat_supplier' => 'jl.panglayungan',
    'created_at' => '2026-09-09 14:18:16',
    'created_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
));
        }

        if (DB::table('tb_pelanggan')->count() === 0) {
            DB::table('tb_pelanggan')->insert(array (
  0 => 
  array (
    'id_pelanggan' => 1,
    'id_kelompok_pelanggan' => NULL,
    'nama_pelanggan' => 'fauzian',
    'telepon' => '082347103',
    'alamat' => 'andalusia miis',
    'created_at' => '2026-09-10 00:11:48',
    'created_by' => 1,
    'updated_at' => '2026-09-10 00:11:59',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
));
        }

        if (DB::table('tb_user')->count() === 0) {
            DB::table('tb_user')->insert(array (
  0 => 
  array (
    'id_user' => 1,
    'id_sekolah' => 1,
    'id_role' => 2,
    'username' => 'admin_smkn1',
    'password' => '$2y$12$BByB7LJshFsGUGSn4jaqz.igcl2zFdDXSQ38bdVku2D.Ms6QUZ5e.',
    'nama_lengkap' => 'Admin SMKN 1 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  1 => 
  array (
    'id_user' => 2,
    'id_sekolah' => 1,
    'id_role' => 3,
    'username' => 'kasir_smkn1',
    'password' => '$2y$12$FNRakzrIoeYV4Wnno2wLNu2lxmspIAUc2LEdorWdtuHME2Bpp.jHi',
    'nama_lengkap' => 'Kasir SMKN 1 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  2 => 
  array (
    'id_user' => 3,
    'id_sekolah' => 1,
    'id_role' => 3,
    'username' => 'kasir2_smkn1',
    'password' => '$2y$12$/Lk7wwsm19TNdfIxP.B0yOP9KSTz4mb.UyrHup/kkQ5YSYkGCqjD2',
    'nama_lengkap' => 'Kasir 2 SMKN 1 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  3 => 
  array (
    'id_user' => 6,
    'id_sekolah' => 3,
    'id_role' => 2,
    'username' => 'admin_smkn3',
    'password' => '$2y$12$EwzqVz9Zr55s63j89z15ruHHqTsCnE3331Xr9w1sDlPKI5LdVm5fK',
    'nama_lengkap' => 'Admin SMKN 3 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  4 => 
  array (
    'id_user' => 7,
    'id_sekolah' => 3,
    'id_role' => 3,
    'username' => 'kasir_smkn3',
    'password' => '$2y$12$rD7t2fXvdUUEo58Y7KNb1Oz45GaTsiSs43waTaOOQFkganCGF4ESW',
    'nama_lengkap' => 'Kasir SMKN 3 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  5 => 
  array (
    'id_user' => 8,
    'id_sekolah' => 4,
    'id_role' => 2,
    'username' => 'admin_smkn4',
    'password' => '$2y$12$gtOcLMPEB23C1LV.ga8dD.xF5nvI3yY5WOw9amk373oeeln6ULSg6',
    'nama_lengkap' => 'Admin SMKN 4 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  6 => 
  array (
    'id_user' => 9,
    'id_sekolah' => 4,
    'id_role' => 3,
    'username' => 'kasir_smkn4',
    'password' => '$2y$12$0DH6cX91f6nK/HxAOW2OJe4srZlVfwp28KWShmLl6zS1weQnQxUFW',
    'nama_lengkap' => 'Kasir SMKN 4 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  7 => 
  array (
    'id_user' => 10,
    'id_sekolah' => 4,
    'id_role' => 3,
    'username' => 'kasir2_smkn4',
    'password' => '$2y$12$bnytFB1aD17OZSbUmsSIj.QF3az51XQH9OJwb9Tl6RZ95cHCwhUOy',
    'nama_lengkap' => 'Kasir 2 SMKN 4 Tasikmalaya',
    'is_active' => 1,
    'created_at' => NULL,
    'created_by' => NULL,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  8 => 
  array (
    'id_user' => 11,
    'id_sekolah' => 1,
    'id_role' => 3,
    'username' => 'kasir SMKN 1 TASIKMALAYA',
    'password' => '$2y$12$jOXjoYkrgRbDtNyXHwtH/ubd/BA7ERKdDEK.DnexjXjJIdf2ghq6u',
    'nama_lengkap' => 'Kasir SMKN 1 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  9 => 
  array (
    'id_user' => 12,
    'id_sekolah' => 1,
    'id_role' => 2,
    'username' => 'admin SMKN 1 TASIKMALAYA',
    'password' => '$2y$12$jOXjoYkrgRbDtNyXHwtH/ubd/BA7ERKdDEK.DnexjXjJIdf2ghq6u',
    'nama_lengkap' => 'Admin SMKN 1 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  10 => 
  array (
    'id_user' => 13,
    'id_sekolah' => 2,
    'id_role' => 3,
    'username' => 'kasir SMKN 2 TASIKMALAYA',
    'password' => '$2y$12$MhVgGmHGCo8syONAQut5/OHdmMNwgjrBMJke9VNOWBKzFHirxtlxS',
    'nama_lengkap' => 'kasir_smkn2',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => '2026-09-15 02:27:02',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  11 => 
  array (
    'id_user' => 14,
    'id_sekolah' => 2,
    'id_role' => 2,
    'username' => 'admin SMKN 2 TASIKMALAYA',
    'password' => '$2y$12$DxlNYRajqsEtbMZkV4zirew2naWPu5p28zVNkAhjTUuYDrd8xsXj6',
    'nama_lengkap' => 'admin_smkn2',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => '2026-09-15 02:26:47',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  12 => 
  array (
    'id_user' => 15,
    'id_sekolah' => 3,
    'id_role' => 3,
    'username' => 'kasir SMKN 3 TASIKMALAYA',
    'password' => '$2y$12$jOXjoYkrgRbDtNyXHwtH/ubd/BA7ERKdDEK.DnexjXjJIdf2ghq6u',
    'nama_lengkap' => 'Kasir SMKN 3 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  13 => 
  array (
    'id_user' => 16,
    'id_sekolah' => 3,
    'id_role' => 2,
    'username' => 'admin SMKN 3 TASIKMALAYA',
    'password' => '$2y$12$jOXjoYkrgRbDtNyXHwtH/ubd/BA7ERKdDEK.DnexjXjJIdf2ghq6u',
    'nama_lengkap' => 'Admin SMKN 3 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  14 => 
  array (
    'id_user' => 17,
    'id_sekolah' => 4,
    'id_role' => 3,
    'username' => 'kasir SMKN 4 TASIKMALAYA',
    'password' => '$2y$12$jOXjoYkrgRbDtNyXHwtH/ubd/BA7ERKdDEK.DnexjXjJIdf2ghq6u',
    'nama_lengkap' => 'Kasir SMKN 4 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  15 => 
  array (
    'id_user' => 18,
    'id_sekolah' => 4,
    'id_role' => 2,
    'username' => 'admin SMKN 4 TASIKMALAYA',
    'password' => '$2y$12$jOXjoYkrgRbDtNyXHwtH/ubd/BA7ERKdDEK.DnexjXjJIdf2ghq6u',
    'nama_lengkap' => 'Admin SMKN 4 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 15:16:37',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  16 => 
  array (
    'id_user' => 20,
    'id_sekolah' => 1,
    'id_role' => 1,
    'username' => 'super admin SMKN 1 TASIKMALAYA',
    'password' => '$2y$12$XHf7O6hV9.flXBApRfNI9.nxYhLJoCh7NvEUwRDQrn20EigJFLzA6',
    'nama_lengkap' => 'Super Admin SMKN 1 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 23:55:43',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  17 => 
  array (
    'id_user' => 21,
    'id_sekolah' => 2,
    'id_role' => 1,
    'username' => 'super admin SMKN 2 TASIKMALAYA',
    'password' => '$2y$12$L7K6MgAmaiKuaeBnjhqQ8e5naPzVCcWR6B5L4EE9RZxWal8ogbuFG',
    'nama_lengkap' => 'SuperAdmin_smkn2',
    'is_active' => 1,
    'created_at' => '2026-09-09 23:55:43',
    'created_by' => 1,
    'updated_at' => '2026-09-15 00:08:15',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  18 => 
  array (
    'id_user' => 22,
    'id_sekolah' => 3,
    'id_role' => 1,
    'username' => 'super admin SMKN 3 TASIKMALAYA',
    'password' => '$2y$12$XHf7O6hV9.flXBApRfNI9.nxYhLJoCh7NvEUwRDQrn20EigJFLzA6',
    'nama_lengkap' => 'Super Admin SMKN 3 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 23:55:43',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  19 => 
  array (
    'id_user' => 23,
    'id_sekolah' => 4,
    'id_role' => 1,
    'username' => 'super admin SMKN 4 TASIKMALAYA',
    'password' => '$2y$12$XHf7O6hV9.flXBApRfNI9.nxYhLJoCh7NvEUwRDQrn20EigJFLzA6',
    'nama_lengkap' => 'Super Admin SMKN 4 Tasikmalaya',
    'is_active' => 1,
    'created_at' => '2026-09-09 23:55:43',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  20 => 
  array (
    'id_user' => 24,
    'id_sekolah' => NULL,
    'id_role' => 4,
    'username' => 'Developer Website',
    'password' => '$2y$12$sMopJOPG5wmckrcWpOwaR.ykHqR7wtiQFQ0THw4C0YHXumYHTV0zy',
    'nama_lengkap' => 'Developer EduMart',
    'is_active' => 1,
    'created_at' => '2026-09-10 18:23:44',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
  21 => 
  array (
    'id_user' => 30,
    'id_sekolah' => 6,
    'id_role' => 1,
    'username' => 'super admin SMPN 1 TASIKMALAYA',
    'password' => '$2y$12$RFeTQDJPEzdloDosPYkj4.J0HDZyAZIlK4Rh6iQepfVcnNdgbW1RW',
    'nama_lengkap' => 'SuperAdmin-smpn1',
    'is_active' => 1,
    'created_at' => '2026-09-14 04:30:05',
    'created_by' => 1,
    'updated_at' => NULL,
    'updated_by' => NULL,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
  ),
));
        }

        if (DB::table('tb_barang')->count() === 0) {
            DB::table('tb_barang')->insert(array (
  0 => 
  array (
    'id_barang' => 1,
    'id_sekolah' => 1,
    'barcode' => 'BRG001',
    'nama' => 'Pulpen Standard',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '2500.00',
    'harga_jual' => '4000.00',
    'stok' => 99,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  1 => 
  array (
    'id_barang' => 2,
    'id_sekolah' => 1,
    'barcode' => 'BRG002',
    'nama' => 'Pensil 2B',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '2000.00',
    'harga_jual' => '3500.00',
    'stok' => 80,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  2 => 
  array (
    'id_barang' => 3,
    'id_sekolah' => 1,
    'barcode' => 'BRG003',
    'nama' => 'Buku Tulis',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '3500.00',
    'harga_jual' => '5000.00',
    'stok' => 74,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 08:04:16',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  3 => 
  array (
    'id_barang' => 4,
    'id_sekolah' => 1,
    'barcode' => 'BRG004',
    'nama' => 'Penghapus',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '1500.00',
    'harga_jual' => '2500.00',
    'stok' => 60,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  4 => 
  array (
    'id_barang' => 5,
    'id_sekolah' => 1,
    'barcode' => 'BRG005',
    'nama' => 'Penggaris 30cm',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '3000.00',
    'harga_jual' => '5000.00',
    'stok' => 50,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  5 => 
  array (
    'id_barang' => 6,
    'id_sekolah' => 1,
    'barcode' => 'BRG006',
    'nama' => 'Spidol Hitam',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '4000.00',
    'harga_jual' => '6500.00',
    'stok' => 40,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  6 => 
  array (
    'id_barang' => 7,
    'id_sekolah' => 1,
    'barcode' => 'BRG007',
    'nama' => 'Kertas HVS A4',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'rim',
    'harga_beli' => '45000.00',
    'harga_jual' => '55000.00',
    'stok' => 24,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  7 => 
  array (
    'id_barang' => 8,
    'id_sekolah' => 1,
    'barcode' => 'BRG008',
    'nama' => 'Map Plastik',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '2500.00',
    'harga_jual' => '4000.00',
    'stok' => 140,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  8 => 
  array (
    'id_barang' => 9,
    'id_sekolah' => 1,
    'barcode' => 'BRG009',
    'nama' => 'Tip-Ex Cair',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '5000.00',
    'harga_jual' => '7500.00',
    'stok' => 35,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  9 => 
  array (
    'id_barang' => 10,
    'id_sekolah' => 1,
    'barcode' => 'BRG010',
    'nama' => 'Stabilo',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '5500.00',
    'harga_jual' => '8000.00',
    'stok' => 45,
    'is_active' => 1,
    'created_at' => '2026-09-09 09:43:53',
    'created_by' => 1,
    'updated_at' => '2026-09-09 09:43:53',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 09:43:53',
    'deleted_by' => 0,
    'is_delete' => 0,
  ),
  10 => 
  array (
    'id_barang' => 11,
    'id_sekolah' => 1,
    'barcode' => 'UJI999',
    'nama' => 'Barang Uji Otomatis R2',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '1000.00',
    'harga_jual' => '2500.00',
    'stok' => 50,
    'is_active' => 0,
    'created_at' => '2026-09-09 07:40:04',
    'created_by' => 1,
    'updated_at' => '2026-09-09 07:40:04',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 07:40:04',
    'deleted_by' => 1,
    'is_delete' => 1,
  ),
  11 => 
  array (
    'id_barang' => 12,
    'id_sekolah' => 1,
    'barcode' => NULL,
    'nama' => 'tes aja',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '2000.00',
    'harga_jual' => '2500.00',
    'stok' => 20,
    'is_active' => 0,
    'created_at' => '2026-09-09 07:44:23',
    'created_by' => 1,
    'updated_at' => '2026-09-09 07:44:23',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 14:14:52',
    'deleted_by' => 1,
    'is_delete' => 1,
  ),
  12 => 
  array (
    'id_barang' => 13,
    'id_sekolah' => 2,
    'barcode' => 'BRC2002',
    'nama' => 'Roti Aoka',
    'id_kategori' => 2,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '50000.00',
    'harga_jual' => '3000.00',
    'stok' => 30,
    'is_active' => 0,
    'created_at' => '2026-09-09 13:40:49',
    'created_by' => 1,
    'updated_at' => '2026-09-09 13:40:49',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 13:50:17',
    'deleted_by' => 1,
    'is_delete' => 1,
  ),
  13 => 
  array (
    'id_barang' => 14,
    'id_sekolah' => 1,
    'barcode' => 'UJI-PINDAH',
    'nama' => 'Barang Uji Pindah',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 1,
    'id_supplier' => 1,
    'satuan' => 'pcs',
    'harga_beli' => '1000.00',
    'harga_jual' => '2000.00',
    'stok' => 5,
    'is_active' => 0,
    'created_at' => '2026-09-09 13:58:25',
    'created_by' => 1,
    'updated_at' => '2026-09-09 13:58:25',
    'updated_by' => 1,
    'deleted_at' => '2026-09-09 13:58:25',
    'deleted_by' => 1,
    'is_delete' => 1,
  ),
  14 => 
  array (
    'id_barang' => 15,
    'id_sekolah' => 2,
    'barcode' => 'BRC2901',
    'nama' => 'Teh gelas',
    'id_kategori' => 5,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '30000.00',
    'harga_jual' => '1000.00',
    'stok' => 28,
    'is_active' => 1,
    'created_at' => '2026-09-09 14:10:57',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:10:57',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  15 => 
  array (
    'id_barang' => 16,
    'id_sekolah' => 2,
    'barcode' => 'BRC2871',
    'nama' => 'Pulpen Joyko',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 9,
    'id_supplier' => 3,
    'satuan' => 'pcs',
    'harga_beli' => '20000.00',
    'harga_jual' => '1500.00',
    'stok' => 16,
    'is_active' => 1,
    'created_at' => '2026-09-09 14:13:47',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:19:35',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  16 => 
  array (
    'id_barang' => 17,
    'id_sekolah' => 2,
    'barcode' => 'BRC3912',
    'nama' => 'dasi',
    'id_kategori' => 7,
    'id_kelompok_kategori' => 10,
    'id_supplier' => 4,
    'satuan' => 'pcs',
    'harga_beli' => '500000.00',
    'harga_jual' => '40000.00',
    'stok' => 24,
    'is_active' => 0,
    'created_at' => '2026-09-09 14:19:17',
    'created_by' => 1,
    'updated_at' => '2026-09-09 14:19:17',
    'updated_by' => 1,
    'deleted_at' => '2026-09-11 00:18:00',
    'deleted_by' => 1,
    'is_delete' => 1,
  ),
  17 => 
  array (
    'id_barang' => 18,
    'id_sekolah' => 2,
    'barcode' => 'BRC2542',
    'nama' => 'baju PSAS',
    'id_kategori' => 8,
    'id_kelompok_kategori' => 10,
    'id_supplier' => 4,
    'satuan' => 'pcs',
    'harga_beli' => '400000.00',
    'harga_jual' => '30000.00',
    'stok' => 36,
    'is_active' => 1,
    'created_at' => '2026-09-10 00:02:23',
    'created_by' => 1,
    'updated_at' => '2026-09-10 00:02:23',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  18 => 
  array (
    'id_barang' => 19,
    'id_sekolah' => 2,
    'barcode' => 'BRC8234',
    'nama' => 'Roti Aoka',
    'id_kategori' => 4,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '50000.00',
    'harga_jual' => '3000.00',
    'stok' => 33,
    'is_active' => 1,
    'created_at' => '2026-09-10 00:03:16',
    'created_by' => 1,
    'updated_at' => '2026-09-17 13:50:18',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  19 => 
  array (
    'id_barang' => 20,
    'id_sekolah' => 2,
    'barcode' => 'BRC9273',
    'nama' => 'dasi',
    'id_kategori' => 9,
    'id_kelompok_kategori' => 11,
    'id_supplier' => 4,
    'satuan' => 'pcs',
    'harga_beli' => '200000.00',
    'harga_jual' => '15000.00',
    'stok' => 29999,
    'is_active' => 1,
    'created_at' => '2026-09-11 00:19:31',
    'created_by' => 1,
    'updated_at' => '2026-09-11 00:19:31',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  20 => 
  array (
    'id_barang' => 21,
    'id_sekolah' => 2,
    'barcode' => 'BRC9724',
    'nama' => 'Penggaris 30CM Joyco',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 9,
    'id_supplier' => 3,
    'satuan' => 'pcs',
    'harga_beli' => '100000.00',
    'harga_jual' => '5000.00',
    'stok' => 28,
    'is_active' => 1,
    'created_at' => '2026-09-11 00:21:20',
    'created_by' => 1,
    'updated_at' => '2026-09-11 00:21:20',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  21 => 
  array (
    'id_barang' => 22,
    'id_sekolah' => 2,
    'barcode' => 'BRC8321',
    'nama' => 'tes',
    'id_kategori' => 1,
    'id_kelompok_kategori' => 9,
    'id_supplier' => 3,
    'satuan' => 'pcs',
    'harga_beli' => '100000.00',
    'harga_jual' => '20000.00',
    'stok' => 100,
    'is_active' => 0,
    'created_at' => '2026-09-14 01:00:19',
    'created_by' => 1,
    'updated_at' => '2026-09-14 01:00:19',
    'updated_by' => 1,
    'deleted_at' => '2026-09-14 01:00:28',
    'deleted_by' => 1,
    'is_delete' => 1,
  ),
  22 => 
  array (
    'id_barang' => 23,
    'id_sekolah' => 2,
    'barcode' => 'BRC1932',
    'nama' => 'risol mayo',
    'id_kategori' => 4,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '50000.00',
    'harga_jual' => '1000.00',
    'stok' => 45,
    'is_active' => 1,
    'created_at' => '2026-09-15 05:42:23',
    'created_by' => 1,
    'updated_at' => '2026-09-15 05:42:23',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  23 => 
  array (
    'id_barang' => 24,
    'id_sekolah' => 2,
    'barcode' => 'BRC9281',
    'nama' => 'Ale-ale',
    'id_kategori' => 5,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '50000.00',
    'harga_jual' => '1000.00',
    'stok' => 45,
    'is_active' => 1,
    'created_at' => '2026-09-15 05:43:37',
    'created_by' => 1,
    'updated_at' => '2026-09-15 05:43:37',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  24 => 
  array (
    'id_barang' => 26,
    'id_sekolah' => 2,
    'barcode' => '8996006858030',
    'nama' => 'Teh botol less sugar',
    'id_kategori' => 5,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '50000.00',
    'harga_jual' => '3000.00',
    'stok' => 20,
    'is_active' => 1,
    'created_at' => '2026-09-15 12:44:10',
    'created_by' => 1,
    'updated_at' => '2026-09-15 12:44:10',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  25 => 
  array (
    'id_barang' => 27,
    'id_sekolah' => 2,
    'barcode' => '089686598056',
    'nama' => 'Chitato Sapi Panggang',
    'id_kategori' => 4,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '50000.00',
    'harga_jual' => '2000.00',
    'stok' => 19,
    'is_active' => 1,
    'created_at' => '2026-09-15 12:48:52',
    'created_by' => 1,
    'updated_at' => '2026-09-15 12:48:52',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  26 => 
  array (
    'id_barang' => 28,
    'id_sekolah' => 2,
    'barcode' => '8997035563544',
    'nama' => 'Otsuka POCARI SWEAT 350ml',
    'id_kategori' => 5,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '100000.00',
    'harga_jual' => '3000.00',
    'stok' => 20,
    'is_active' => 1,
    'created_at' => '2026-09-16 08:02:34',
    'created_by' => 1,
    'updated_at' => '2026-09-16 08:02:34',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
  27 => 
  array (
    'id_barang' => 29,
    'id_sekolah' => 2,
    'barcode' => '8990044000000',
    'nama' => 'Glico Pocky chocolate',
    'id_kategori' => 4,
    'id_kelompok_kategori' => 5,
    'id_supplier' => 2,
    'satuan' => 'pcs',
    'harga_beli' => '100000.00',
    'harga_jual' => '2000.00',
    'stok' => 30,
    'is_active' => 1,
    'created_at' => '2026-09-18 13:54:02',
    'created_by' => 1,
    'updated_at' => '2026-09-18 13:54:02',
    'updated_by' => 1,
    'deleted_at' => NULL,
    'deleted_by' => NULL,
    'is_delete' => 0,
  ),
));
        }

    }
}
